### PR TITLE
Adding configuration options for ports

### PR DESCRIPTION
**Pull request by bdelwood**
Adding values to customize the ports the server listens to. Per https://github.com/lloesche/valheim-server-docker/issues/369 only the game port and game port +1 are in use, so the previous game3 port was unneeded. 

Also added relevant docs.

### CODE REVIEW

**Comment by Addyvan** [comment]
lgtm, merging in and will release a new version of the chart after I test out the rendering.

**Comment by Addyvan** [comment]
thanks @bdelwood

**Comment by Addyvan** [comment]
@bdelwood Tested it out and added released [a new version of the chart](https://github.com/Addyvan/valheim-k8s/releases/tag/valheim-k8s-1.0.4).

**Comment by bdelwood** [comment]
Thanks! That was quick! Couldn't even write my other PR for the http status changes.

**Pull request merged**
